version: "3"

services:
  front:
    build: ./front
    container_name: front
    restart: always
    links:
      - api
    depends_on:
      - api

  api:
    build: ./api
    container_name: api
    restart: always
    depends_on:
      - mongodb
    links:
      - mongodb

  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro

  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
