version: "3"

services:
  front:
    build: ./front
    container_name: front
    volumes:
      - ./front:/app
      - /app/node_modules
    restart: always
    # ports:
    #   - 80:3000
    links:
      - api
    depends_on:
      - api

  api:
    build: ./api
    container_name: api
    # ports:
    #   - 8080:5000
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: always
    depends_on:
      - mongodb
    links:
      - mongodb

  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: always
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro

  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
