version: "3"

services:
  front:
    build: ./front
    container_name: front
    depends_on:
      - api

  api:
    build: ./api
    container_name: api

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - api
